<a href="https://colab.research.google.com/github/resulcaliskan/projects/blob/master/Keras_Fashion_MNIST_Images_Classification_Using_CNNs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# CODE TO CLASSIFY IMAGES (CIFAR-10) USING CNNs



# STEP 0: PROBLEM STATEMENT

- CIFAR-10 is a dataset that consists of several images divided into the following 10 classes: 
    - Airplanes
    - Cars 
    - Birds
    - Cats
    - Deer
    - Dogs
    - Frogs
    - Horses
    - Ships
    - Trucks

- The dataset stands for the Canadian Institute For Advanced Research (CIFAR)
- CIFAR-10 is widely used for machine learning and computer vision applications. 
- The dataset consists of 60,000 32x32 color images and 6,000 images of each class.
- Images have low resolution (32x32). 
- Data Source: https://www.cs.toronto.edu/~kriz/cifar.html


# STEP #1: IMPORT LIBRARIES/DATASETS

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn 

In [0]:
from keras.datasets import fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [0]:
# reshape dataset to have a single channel
X_train = X_train.reshape((X_train.shape[0], 28, 28, 1))
X_test = X_test.reshape((X_test.shape[0], 28, 28, 1))

In [56]:
X_train.shape

(60000, 28, 28, 1)

In [57]:
X_test.shape

(10000, 28, 28, 1)

In [58]:
y_train.shape

(60000,)

In [59]:
y_test.shape

(10000,)

# STEP #2: VISUALIZE DATA

In [0]:
i = 30009
plt.imshow(X_train[i])
print(y_train[i])

In [0]:
W_grid = 8
L_grid = 8

fig, axes = plt.subplots(L_grid, W_grid, figsize = (20,20))
axes = axes.ravel()

n_training = len(X_train)

for i in np.arange(0, L_grid * W_grid):
    index = np.random.randint(0, n_training) # pick a random number
    axes[i].imshow(X_train[index])
    axes[i].set_title(y_train[index])
    axes[i].axis('off')
    
plt.subplots_adjust(hspace = 0.4)

In [17]:
n_training

60000

# STEP #3: DATA PREPARATION

In [0]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [0]:
number_cat = 10

In [65]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [0]:
import keras
y_train = keras.utils.to_categorical(y_train, number_cat)

In [67]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
y_test = keras.utils.to_categorical(y_test, number_cat)

In [69]:
y_test

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
X_train = X_train/255
X_test = X_test/255


In [72]:
X_train.shape

(60000, 28, 28, 1)

In [0]:
Input_shape = X_train.shape[1:]

In [74]:
Input_shape

(28, 28, 1)

# STEP #4: TRAIN THE MODEL

In [0]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, Dense, Flatten, Dropout
from keras.optimizers import Adam
from keras.callbacks import TensorBoard

In [0]:
cnn_model = Sequential()
cnn_model.add(Conv2D(filters = 64, kernel_size = (3,3), activation = 'relu', input_shape = Input_shape ))
cnn_model.add(Conv2D(filters = 64, kernel_size = (3,3), activation = 'relu'))
cnn_model.add(MaxPooling2D(2,2))
cnn_model.add(Dropout(0.3))


cnn_model.add(Conv2D(filters = 128, kernel_size = (3,3), activation = 'relu'))
cnn_model.add(Conv2D(filters = 128, kernel_size = (3,3), activation = 'relu'))
cnn_model.add(MaxPooling2D(2,2))
cnn_model.add(Dropout(0.3))

cnn_model.add(Flatten())

cnn_model.add(Dense(units = 1024, activation = 'relu'))
cnn_model.add(Dropout(0.25))
cnn_model.add(Dense(units = 1024, activation = 'relu'))
cnn_model.add(Dropout(0.25))
cnn_model.add(Dense(units = 512, activation = 'relu'))
cnn_model.add(Dense(units = 10, activation = 'softmax'))

In [0]:
cnn_model.compile(loss = 'categorical_crossentropy', optimizer = "adam", metrics = ['accuracy'])

In [78]:
history = cnn_model.fit(X_train, y_train, batch_size = 32, epochs = 50, shuffle = True)

W0901 14:47:01.664186 139688642017152 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/50
60000/60000 [==============================] - 25s 418us/step - loss: 0.5075 - acc: 0.8108
Epoch 2/50
60000/60000 [==============================] - 17s 276us/step - loss: 0.3339 - acc: 0.8798
Epoch 3/50
60000/60000 [==============================] - 17s 276us/step - loss: 0.2949 - acc: 0.8950
Epoch 4/50
60000/60000 [==============================] - 16s 275us/step - loss: 0.2701 - acc: 0.9031
Epoch 5/50
60000/60000 [==============================] - 17s 278us/step - loss: 0.2526 - acc: 0.9089
Epoch 6/50
60000/60000 [==============================] - 17s 276us/step - loss: 0.2404 - acc: 0.9132
Epoch 7/50
60000/60000 [==============================] - 17s 278us/step - loss: 0.2290 - acc: 0.9177
Epoch 8/50
60000/60000 [==============================] - 17s 279us/step - loss: 0.2247 - acc: 0.9186
Epoch 9/50
60000/60000 [==============================] - 17s 278us/step - loss: 0.2180 - acc: 0.9204
Epoch 10/50
60000/60000 [==============================] - 17s 278us/step - loss: 

# STEP #5: EVALUATE THE MODEL

In [79]:
evaluation = cnn_model.evaluate(X_test, y_test)
print('Test Accuracy: {}'.format(evaluation[1]))

10000/10000 [==============================] - 1s 92us/step
Test Accuracy: 0.9253


In [80]:
predicted_classes = cnn_model.predict_classes(X_test) 
predicted_classes

array([9, 2, 1, ..., 8, 1, 5])

In [81]:
y_test

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
y_test = y_test.argmax(1)

In [83]:
y_test

array([9, 2, 1, ..., 8, 1, 5])

In [0]:
L = 7
W = 7
fig, axes = plt.subplots(L, W, figsize = (12, 12))
axes = axes.ravel()

for i in np.arange(0, L*W):
    axes[i].imshow(X_test[i])
    axes[i].set_title('Prediction = {}\n True = {}'.format(predicted_classes[i], y_test[i]))
    axes[i].axis('off')

plt.subplots_adjust(wspace = 1)    

In [0]:
from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, predicted_classes)
cm
plt.figure(figsize = (10, 10))
sns.heatmap(cm, annot = True)

# STEP #6: SAVING THE MODEL

In [0]:
import os 
directory = os.path.join(os.getcwd(), 'saved_models')

if not os.path.isdir(directory):
    os.makedirs(directory)
model_path = os.path.join(directory, 'keras_fashion_mnist_trained_model.h5')
cnn_model.save(model_path)

# STEP #7: IMPROVING THE MODEL WITH DATA AUGMENTATION

- Image Augmentation is the process of artificially increasing the variations of the images in the datasets by flipping, enlarging, rotating the original images. 
- Augmentations also include shifting and changing the brightness of the images.

# STEP 7 MODEL TRAINING USING AUGEMENTED DATASET

In [0]:
from keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
                            rotation_range = 90,
                            width_shift_range = 0.1,
                            horizontal_flip = True,
                            vertical_flip = True
                             )

In [0]:
datagen.fit(X_train)

In [89]:
cnn_model.fit_generator(datagen.flow(X_train, y_train, batch_size = 32), epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 20s 11ms/step - loss: 1.8329 - acc: 0.2800
Epoch 2/5
1875/1875 [==============================] - 20s 11ms/step - loss: 1.5086 - acc: 0.4152
Epoch 3/5
1875/1875 [==============================] - 20s 11ms/step - loss: 1.2649 - acc: 0.5289
Epoch 4/5
1875/1875 [==============================] - 20s 11ms/step - loss: 1.0726 - acc: 0.6106
Epoch 5/5
1875/1875 [==============================] - 20s 11ms/step - loss: 0.9611 - acc: 0.6491


In [0]:
# save the model
directory = os.path.join(os.getcwd(), 'saved_models')

if not os.path.isdir(directory):
    os.makedirs(directory)
model_path = os.path.join(directory, 'keras_fashion_mnist_trained_model_Augmentation.h5')
cnn_model.save(model_path)

# GREAT JOB! 